import type { CSSProperties } from "react";

export const pfosS: Record<string, CSSProperties> = {
  panel: { maxWidth: 800, margin: "0 auto", padding: "24px 0" },
  baslik: { fontSize: 22, fontWeight: 600, marginBottom: 8, color: "#000" },
  alt: { fontSize: 14, color: "#666", marginBottom: 24, lineHeight: 1.5 },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 10,
    marginBottom: 20,
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 12,
    marginBottom: 24,
  },
  kart: {
    padding: "12px 14px",
    border: "1px solid #ccc",
    background: "#fff",
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
  },
  secili: { border: "2px solid #000", background: "#f5f5f5" },
  kartBaslik: { fontSize: 14, fontWeight: 600, marginBottom: 4, color: "#000" },
  kartAlt: { fontSize: 12, color: "#666", marginBottom: 4 },
  kartMeta: { fontSize: 11, color: "#999" },
  devam: {
    marginTop: 16,
    padding: "12px 28px",
    background: "#000",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontSize: 15,
    fontFamily: "inherit",
  },
  pasif: { background: "#999", cursor: "not-allowed" },
  geri: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 13,
    color: "#666",
    marginBottom: 16,
    padding: 0,
    fontFamily: "inherit",
  },
  alan: { marginBottom: 16 },
  etiket: {
    display: "block",
    fontSize: 14,
    fontWeight: 500,
    marginBottom: 8,
    color: "#333",
  },
  ipucu: { fontWeight: 400, color: "#999", fontSize: 12 },
  input: {
    width: "100%",
    padding: "10px 12px",
    border: "1px solid #ccc",
    fontSize: 16,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  radyoGrup: { display: "flex", gap: 10, flexWrap: "wrap" },
  radyo: {
    padding: "10px 20px",
    border: "1px solid #ccc",
    background: "#fff",
    cursor: "pointer",
    fontSize: 14,
    fontFamily: "inherit",
  },
  bilgi: { color: "#999", fontSize: 14 },
  hata: { color: "#c00", fontSize: 13, marginBottom: 12 },
  sonucUst: { padding: "16px 0", borderBottom: "1px solid #eee", marginBottom: 16 },
  bolumSatir: {
    display: "grid",
    gridTemplateColumns: "1fr 100px",
    gap: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  bolumListe: {
    border: "1px solid #eee",
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
  },
  stepNav: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 28,
    paddingBottom: 16,
    borderBottom: "1px solid #eee",
  },
  stepPill: {
    fontSize: 12,
    padding: "6px 12px",
    borderRadius: 20,
    border: "1px solid #ddd",
    color: "#666",
  },
  stepPillActive: {
    border: "2px solid #000",
    color: "#000",
    fontWeight: 600,
  },
  stepPillDone: { background: "#f5f5f5", color: "#333" },
};
