/** Şablon urunTipi → zone/shop tip_kodu (legacy motor ile hizalı) */
export const URUN_TIPI_ALIASES: Record<string, string> = {
  "espresso-2-grup": "espresso_makinasi",
  "kahve-degirmeni": "kahve_degirmeni",
  "buz-makinesi": "buz_makinesi",
  "buz-makinesi-90kg": "buz_makinesi",
  "bar-blender": "bar_blender",
  "blender-bar": "bar_blender",
  "smoothie-blender": "bar_blender",
  "glass-washer": "bardak_yikama",
  davlumbaz: "davlumbaz_duvar",
  "davlumbaz-izgara": "davlumbaz_duvar",
  "davlumbaz-et-hazirlik": "davlumbaz_duvar",
  "combi-firin": "kombi_firin_6t",
  "izgara-gazli": "char_broil",
  "izgara-setustü": "char_broil",
  "komurlu-izgara": "komurlu_izgara",
  "plate-izgara-gazli": "char_broil",
  "lavash-izgara-gazli": "char_broil",
  "dokum-izgara-gazli": "char_broil",
  "ocak-4-gozlu": "ocak_4gz",
  "ocak-2-gozlu": "ocak_4gz",
  "friteuse-cift-hazneli": "fritoz_tek",
  "friteuse-setustü": "fritoz_tek",
  "vakum-makinesi": "vakum_makinesi",
  "kemik-testere": "kemik_testere",
  "kiyma-makinasi-no32": "kiyma_makinesi",
  "dilimleme-makinesi": "dilimleme_makinesi",
  "sarap-dolabi": "sarap_dolabi",
  salamander: "salamander",
  "kuru-depo-raf": "istif_rafi",
  "depo-buzdolabi-tek-kapili": "dik_tip_buzdolabi",
  "dik-buzdolabı-depo": "dik_tip_buzdolabi",
  "depo-derin-dondurucu": "derin_dondurucu_dik",
  "derin-dondurucu-depo": "derin_dondurucu_dik",
  "bulasik-makinesi-giyotin": "bulasik_giyotin_1000",
  "bulasik-makinesi-setalti": "bulasik_setalti",
  "bulasik-makinesi-kapasiteli": "bulasik_giyotin_1000",
  "cop-siyirma-tezgahi": "cop_siyirma_tez",
  "bym-cikis-tezgahi": "bym_cikis_tez",
  "bulasik-cikis-tezgahi": "bym_cikis_tez",
  "spiral-mikser-hamur": "spiral_hamur",
  "hamur-yogurma-35lt": "spiral_hamur",
  "hamur-yogurma-50lt": "spiral_hamur",
  "mikrodalgali-firin": "mikrodalga_firin",
  "calisma-tezgahi-cekmeceli": "calisma_tezgahi",
  "bar-sogutucu-setaltı": "bar_buzdolabi",
  "tezgah-buzdolabi-3-kapili": "tezgah_tip_buzdolabi",
  "tezgah-tip-buzdolabi": "tezgah_tip_buzdolabi",
  "cihazalti-buzdolabi-cekme": "tezgah_alti_buz_cek",
  "hazirlik-buzdolabi": "tezgah_tip_buzdolabi",
  "soguk-hazirlik-tezgahi": "sogutma_tezgah",
  "soguk-tesir-dolabi-pastane": "teshir_vitrin",
  "pastane-vitrin-soguk": "teshir_vitrin",
  "konveksiyon-firin-pastane": "raf_firin",
  "pizza-firin-kubbeli": "raf_firin",
  "pizza-firin-kubbeli-gazli": "raf_firin",
  "evye-cift-gozlu": "tezgah_evyeli",
  "konveksiyon-firin-unox": "raf_firin",
  "patisserie-firin": "raf_firin",
  "pide-pizza-firin": "pizza_firini_kubbeli_gaz",
  "mikrodalga-firin": "mikrodalga_firin",
  "tas-firin": "tas_tabanli_firin",
  "buz-makinesi-brema-cb416": "buz_makinesi_brema_42",
  "buz-makinesi-brema-cb425": "buz_makinesi_brema_48",
  "pizza-firin-tas-tabanli": "tas_tabanli_firin",
  "speed-oven-merry-chef": "mikrodalga_firin",
  "sise-sogutucu-2-kapili": "sise_sogutucu_2k",
  "sise-sogutucu-3-kapili": "sise_sogutucu_3k",
  "calisma-tezgahi-kasa-kahve": "calisma_tezgahi",
  "calisma-tezgahi-dolapli": "calisma_tezgahi_dolap",
  "calisma-tezgahi-dolapli-70": "calisma_tezgahi_dolap",
  "calisma-tezgahi-taban-ara": "calisma_tezgahi",
  "calisma-tezgahi-taban-ara-dolapli": "calisma_tezgahi",
  "calisma-tezgahi-taban-ara-90": "calisma_tezgahi",
  "calisma-tezgahi-taban-ara-dolapli-90": "calisma_tezgahi",
  "calisma-tezgahi-dolapli-2": "calisma_tezgahi_dolap",
  "icecek-havuzu-soguk": "icecek_havuzu_soguk",
  "depo-derin-dondurucu-cift-kapili": "derin_dondurucu_dik",
  "setalti-derin-dondurucu": "setalti_derin_dondurucu",
  "setalti-buzdolabi-tek": "setalti_buzdolabi",
  "setaltı-buzdolabi": "setalti_buzdolabi",
  "filter-coffee-makinesi-2": "filter_coffee",
  "montaj-nakliye": "montaj_nakliye",
  "mikser-planet": "spiral_hamur",
  "heat-lamp-servis": "mikrodalga_firin",
  "waffle-makinesi": "mikrodalga_firin",
  "sicak-yemek-display": "teshir_vitrin",
  "saladette": "sogutma_tezgah",
  "pizza-prep-tezgahi": "sogutma_tezgah",
  "dizden-kumandalı-evye": "tezgah_evyeli",
  "dizden-kumandali-evye": "tezgah_evyeli",
  "cop-tezgahi": "cop_tezgahi",
  "cop-arabasi": "cop_arabasi",
  "evye-tezgahi-dolapli": "evye_tezgah_dolap",
  "bar-kuvet-40": "bar_kuvet",
  "rinser-evyesi": "rinser_evye",
  "kahve-makinasi-turk": "turk_kahve_cift",
  "kati-meyve-sikacagi": "meyve_sikacagi",
  "bar-mikser": "bar_mikser",
  "yer-izgara-kucuk": "yer_izgara",
  "filter-coffee-makinesi": "filter_coffee",
  "turk-kahvesi-makinasi": "turk_kahve_cift",
  "turk-kahvesi-makinesi": "turk_kahve_cift",
};

/** tip_kodu → ekipmanlar.json adında aranacak kelimeler */
export const TIP_SEARCH_TERMS: Record<string, string[]> = {
  kombi_firin_6t: ["kombili", "icombi", "combi", "kombi firin"],
  davlumbaz_duvar: ["davlumbaz", "duvar"],
  ocak_4gz: ["4", "gözlü", "gozlu", "ocak", "alevli"],
  tezgah_alti_buz_cek: ["cihazaltı", "cihaz alti", "tezgah altı", "tezgahalti", "setaltı buzdolab"],
  calisma_tezgahi: ["çalışma tezgah", "calisma tezgah"],
  tezgah_evyeli: ["evyeli tezgah", "tek evye", "çift evye"],
  duvar_rafi: ["duvar raf"],
  cop_arabasi: ["çöp", "cop kova"],
  yer_izgara: ["yer ızgar", "yer izgar"],
  komurlu_izgara: ["komurlu izgar", "kömürlü izgar"],
  istif_rafi: ["istif raf", "istif rafi", "demonte"],
  tezgah_tip_buzdolabi: ["tezgah tipi buzdolab", "tezgah tip buzdolab"],
  mikrodalga_firin: ["mikrodalga"],
  servis_rafi: ["servis arab", "servis raf"],
  fritoz_tek: ["fritöz", "fritoz"],
  char_broil: ["plate ızgar", "plate izgar", "charbroil", "kontakt ızgar"],
  salamander: ["salamander"],
  tezgah_duz: ["nötr", "notr", "ara tezgah"],
  dilimleme_makinesi: ["dilimleme", "gıda dilimleme", "gida dilimleme"],
  kiyma_makinesi: ["kıyma", "kiyma", "et kıyma"],
  kemik_testere: ["kemik testere", "kemik tester"],
  vakum_makinesi: ["vakum", "vakuum"],
  dik_tip_buzdolabi: ["dik tip buzdolab"],
  cop_siyirma_tez: ["sıyırma", "siyirma", "bulaşık sıyır"],
  bym_cikis_tez: ["makine çıkış", "cikis tezgah", "çıkış tezgah"],
  bulasik_giyotin_1000: ["giyotin", "1000 tabak", "1000 tb"],
  bulasik_setalti: ["tezgahalti", "tezgah alti", "oby 50", "setalti bulasik"],
  sogutma_tezgah: ["soğutmalı tezgah", "sogutmali tezgah", "hazırlık buzdolab", "saladette", "pizza prep"],
  derin_dondurucu_dik: ["dik tip derin", "derin dondurucu"],
  spiral_hamur: ["spiral", "hamur yoğur", "planet mikser", "planet"],
  raf_firin: ["raflı fırın", "rafli firin", "pastane fırın", "bakertop", "unox"],
  tas_tabanli_firin: ["taş taban", "tas taban", "stone"],
  espresso_makinasi: ["espresso", "2 gruplu", "2 grupl", "kahve makinas"],
  kahve_degirmeni: ["değirmen", "degirmen", "kahve öğüt", "grinder"],
  bar_blender: ["bar blender", "mikser bar"],
  bar_buzdolabi: ["sishe sogutucu", "şişe soğutucu", "bbc35", "icecek sogutucu", "3 kapili", "içecek soğutucu"],
  buz_makinesi: ["buz makin", "küp buz", "kup buz"],
  sarap_dolabi: ["şarap dolab", "sarap dolab"],
  bardak_yikama: ["bardak yık", "bardak yik", "undercounter"],
  teshir_vitrin: ["teşhir vitrin", "teshir vitrin", "soğuk vitrin"],
  filter_coffee: ["filtre kahve", "filter kahve", "batch brew", "animo", "m200"],
  turk_kahve_cift: ["türk kahve", "turk kahve", "atkm", "cezveli"],
  sise_sogutucu_2k: ["iki kapili", "2 kapili", "90*50", "icecek dolab"],
  sise_sogutucu_3k: ["uc kapili", "3 kapili", "135*50", "icecek dolab"],
  cop_tezgahi: ["cop tezgah", "çöp tezgah"],
  evye_tezgah_dolap: ["evye tezgah", "evyeli tezgah", "evye dolap"],
  rinser_evye: ["rinser", "durulama", "sprey unitesi"],
  meyve_sikacagi: ["meyve sik", "portakal sik", "katı meyve"],
  bar_mikser: ["bar mikser", "milk frother", "sut kop"],
  calisma_tezgahi_dolap: ["calisma tezgah", "çalışma tezgah", "140*60"],
  bar_kuvet: ["kuvet", "40*40*25"],
  setalti_derin_dondurucu: ["setalti derin", "setaltı derin", "tezgah alti derin", "cihazalti derin"],
  setalti_buzdolabi: [
    "tag 270",
    "yatay tip buzdolab",
    "tezgah tipi",
    "setalti buzdolab",
    "setaltı buzdolab",
    "cihazalti buzdolab",
  ],
  icecek_havuzu_soguk: ["icecek havuzu", "içecek havuzu", "soguk havuz", "soğuk havuz"],
};

export const TIP_SHOP_CATS: Record<string, string[]> = {
  espresso_makinasi: ["espresso", "kahve"],
  kahve_degirmeni: ["kahve"],
  filter_coffee: ["kahve", "filtre"],
  turk_kahve_cift: ["kahve"],
  buz_makinesi: ["buz"],
  kombi_firin_6t: ["kuzineler", "sanayi-ocaklari", "firin"],
  fritoz_tek: ["fritoz"],
  yer_izgara: ["izgar", "ocak"],
  bulasik_giyotin_1000: ["bulasik", "yikama"],
  bulasik_setalti: ["bulasik", "yikama"],
  bardak_yikama: ["bulasik", "yikama", "bardak"],
  bulasik_tunel: ["bulasik", "yikama"],
  bulasik_sepet: ["bulasik", "yikama"],
  tezgah_tip_buzdolabi: ["sogutma"],
  tezgah_alti_buz_cek: ["sogutma"],
  montaj_nakliye: ["yardimci"],
  dik_tip_buzdolabi: ["sogutma"],
  sise_sogutucu_2k: ["sogutma"],
  sise_sogutucu_3k: ["sogutma"],
  bar_buzdolabi: ["sogutma"],
  setalti_buzdolabi: ["sogutma"],
  cop_arabasi: ["yardimci"],
  meyve_sikacagi: ["hazirlik", "icecek"],
  kiyma_makinesi: ["hazirlik", "et-hazirlik"],
  kemik_testere: ["hazirlik", "et-hazirlik"],
  dilimleme_makinesi: ["hazirlik", "et-hazirlik"],
  vakum_makinesi: ["hazirlik"],
  spiral_hamur: ["hazirlik", "hamur"],
  hamur_acma: ["hazirlik", "hamur"],
  patates_soyma: ["hazirlik", "sebze"],
};

export function normalizeTipKodu(value: string): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/-/g, "_")
    .replace(/ı/g, "i")
    .replace(/ğ/g, "g")
    .replace(/ü/g, "u")
    .replace(/ş/g, "s")
    .replace(/ö/g, "o")
    .replace(/ç/g, "c");
}

export function resolveTipKodu(urunTipi: string): string {
  const trimmed = String(urunTipi || "").trim();
  if (/^yer-izgara-\d+$/i.test(trimmed)) return "yer_izgara";
  if (URUN_TIPI_ALIASES[trimmed]) return URUN_TIPI_ALIASES[trimmed];
  return normalizeTipKodu(trimmed);
}
